version: '2'

volumes:
  spotifycache:
  snapcast:
  mpd:

services:

  # Core services
  audio:
    build: ./core/audio
    privileged: true
    labels:
      io.balena.features.dbus: 1
      # To install ./core/audio/piano-firmware/
      io.balena.features.firmware: 1
    ports:
      - 4317:4317
    volumes:
      - snapcast:/var/cache/snapcast

  sound-supervisor:
    build: ./core/sound-supervisor
    network_mode: host
    ports:
      - 3000:3000
    labels:
      io.balena.features.supervisor-api: 1

  multiroom-server:
    build: ./core/multiroom/server
    restart: on-failure
    ports:
      - 1704:1704
    volumes:
      - snapcast:/var/cache/snapcast

  multiroom-client:
    build: ./core/multiroom/client
    restart: on-failure

  # Plugins
  bluetooth:
    build: ./plugins/bluetooth
    restart: on-failure
    network_mode: host
    cap_add:
      - NET_ADMIN
    labels:
      io.balena.features.dbus: 1

  airplay:
    build: ./plugins/airplay
    network_mode: host
    privileged: true
    labels:
      io.balena.features.dbus: 1

  spotify:
    build: ./plugins/spotify
    privileged: true
    network_mode: host
    volumes:
      - spotifycache:/var/cache/raspotify

  upnp:
    build: ./plugins/upnp
    network_mode: host
    ports:
      - 49494:49494

  mpd:
    build: ./plugins/mpd
    # This needs privileges for mounting with cifs
    privileged: true
    network_mode: host
    volumes:
      - mpd:/var/lib/mpd
    ports:
      - 6600:6600

  scrobbler:
    build: ./plugins/scrobbler
    network_mode: host
