FROM balenalib/%%BALENA_MACHINE_NAME%%-debian:sid

RUN install_packages mpd ncmpcpp cifs-utils smbclient pulseaudio nfs-common

# Start app
COPY mpd.conf /etc/mpd.conf

COPY start-mpd.sh /usr/src/start-mpd.sh
COPY mount-cifs.sh /usr/src/mount-cifs.sh

CMD ["/bin/bash", "/usr/src/start-mpd.sh"]
