FROM balenalib/%%BALENA_MACHINE_NAME%%-debian:sid

WORKDIR /usr/src

COPY myMPD /usr/src

RUN /usr/src/build.sh installdeps
RUN /usr/src/build.sh release
RUN /usr/src/build.sh install

COPY mympd.conf /etc/mympd.conf

CMD [ "mympd" ]
