FROM balenalib/%%BALENA_MACHINE_NAME%%-debian:sid

WORKDIR /usr/src

RUN install_packages git

RUN git clone https://github.com/jcorporation/myMPD --branch v6.6.2 /usr/src

RUN /usr/src/build.sh installdeps
RUN /usr/src/build.sh release
RUN /usr/src/build.sh install

COPY mympd.conf /etc/mympd.conf

CMD [ "mympd" ]
