FROM balenaplayground/balenalabs-audio:%%BALENA_MACHINE_NAME%%

# To install piano-firmware
RUN install_packages rsync

WORKDIR /usr/src
COPY . .

RUN install_packages git

RUN git clone https://github.com/allocom/piano-firmware /usr/src/piano-firmware

CMD [ "/bin/bash", "/usr/src/start.sh" ]
